### ISSUE TITLE
Viewer uptate permalink

### ISSUE THREAD

**Issue by rolandcahen** [jonlab/NewAtlantis#30]
Viewer last version should be downloadable from Github with a permalink.
This is needed for the documentation ad other purposes

**Comment by jonlab** [comment]
I am not sure that GitHub is the place for that. What about putting the last build on the website instead ? (www.newatlantis.world)

**Comment by rolandcahen** [comment]
Oui mais il faudra faire les mises à jour à la main.
On trouve souvent des builds sur git!

Roland Cahen
0614892899

**Comment by jonlab** [comment]
I will put links to the website and to the last versions on GITHub.
