### ISSUE TITLE
Audio listener position

### ISSUE THREAD

**Issue by jonlab** [jonlab/NewAtlantis#31]
This is quite obvious for First Person camera, but in the case of a third person camera, is the Audio Listener attached to the camera or to the avatar ?

**Comment by jonlab** [comment]
I think that it should be attached to the camera, to be consistent with what we see on screen.

**Comment by rolandcahen** [comment]
Old question
Right in the middle is a common answer when the cameea isn't too far.
If further away, and all together i'd prefer it to be on the camera, wysyh.

The problem with this is solution is that you may hear level burts and falls  when switching camera.

Roland Cahen
0614892899

**Comment by jonlab** [comment]
yes, you may hear level changes when switching camera, but isn't it what we also want when we switch camera ? swith the audio point of view/hear ?

**Comment by petesinc** [comment]
I think it should (by default) be attached to the camera so that is possible to listen to a distant action however we might have a microphone help at some point (with different capsules) or maybe all helps would transform the avatar into the listener even when it isn't first person?

**Comment by jonlab** [comment]
Ok. 
We could have to use the new Spatializer SDK to achieve the capsules directivity. I don't think that we can do that in a clean way with the built-in panning.
http://docs.unity3d.com/Manual/AudioSpatializerSDK.html

**Comment by jonlab** [comment]
I am closing this for now. Let's test the simple "on camera" Audio Listener and we will discuss alternatives later.
