### ISSUE TITLE
Initial conditions restore component

### ISSUE THREAD

**Issue by jonlab** [jonlab/NewAtlantis#32]
We would need to provide a way for an object to be resetted to a given state during a session : for example an object that can fall down or break into small parts.
A possible implementation would be to have an "InitialStateAutoRestorer" that would maybe restore the object state (=transform of object and children) to the initial state after a given duration...

**Comment by rolandcahen** [comment]
This sounds perfect to me

Roland Cahen
0614892899

**Comment by jonlab** [comment]
component NARestoreTransform implemented.
