### ISSUE TITLE
PortalTeleport Bug

### ISSUE THREAD

**Issue by sachaamm** [jonlab/NewAtlantis#33]
Portal Bug with Chicago space, I can't come back to the lobby 
( after uploading a asset to the chicago space )

**Comment by jonlab** [comment]
Could you be more precise ? What happens ?

**Comment by jonlab** [comment]
I tested and it works :
-start a server at "Lobby".
-go to Chicago portal. We are now in Chicago.
-go to Back portal. We are now back in the lobby.

Try to update the GIT, maybe you are not up to date .
