### ISSUE TITLE
Crash after dl the ENSCI space

### ISSUE THREAD

**Issue by sachaamm** [jonlab/NewAtlantis#36]
when i try to download the test ENSCI space I got crash ???
![error](https://cloud.githubusercontent.com/assets/11826078/11724418/9294256c-9f39-11e5-8e94-bb21cebdb55d.png)

**Comment by jonlab** [comment]
This is a crash of the Unity player, this happens sometimes and we can not do much about that.
Reopen the issue if it this happens again and that you can reproduce it.
