### ISSUE TITLE
It takes a while to register to the platform

### ISSUE THREAD

**Issue by sachaamm** [jonlab/NewAtlantis#39]
Mark was trying to register inside the NA platform and it takes a while to connect, registr, like Unity is freeze or we didn't get any response from server.

**Comment by jonlab** [comment]
Could you give more informations :
-PC/Mac ? build ? Unity editor ?
-Did you have an error in the console ?
-Did it eventually succeeded ?
-How long did that take ? (in seconds)
-Where you able to reproduce several times (how many ?)
Maybe that is just an internet connectivity issue on your side ?
I juste tested and it took 1 s to register (between clic on "register" and the login window display).
