### ISSUE TITLE
Minimum resolution for proper GUI is now 1024x768

### ISSUE THREAD

**Issue by sachaamm** [jonlab/NewAtlantis#41]
It's a bit problematic to dev because now i can't see anymore the entire window with this update when im in unity , even I maximize on play. 
So i can't launch a server , and test new features , etc.

**Comment by jonlab** [comment]
The whole screen does not fit when you maximize Unity, select _Maximize on Play_ and click on _Play_ ?
What is your screen resolution ?

**Comment by sachaamm** [comment]
If i maxime on play , my resolution size is 1366 \* 588

**Comment by jonlab** [comment]
588 ? But what native resolution is your screen ?

**Comment by sachaamm** [comment]
1366 \* 768

**Comment by jonlab** [comment]
![capture d ecran 2015-12-14 a 17 49 55](https://cloud.githubusercontent.com/assets/12045398/11787276/1dd1df4e-a28b-11e5-8070-c3a488426918.png)

If you really maximize your Unity app, this fits on 1024x768, does it work for you ?

**Comment by jonlab** [comment]
There is now a scaling of the GUI based on the Screen.height (when < 768).
