### ISSUE TITLE
Accessing ENSCI space test

### ISSUE THREAD

**Issue by sachaamm** [jonlab/NewAtlantis#42]
I open this topic because, even I updated Unity to 5. 3 
I still get some troubles to access to ENSCI space test.
The sound is working but I just  didn't get  access to some materials. I've got the Exception Unity Message :

Unable to open archive file: C:/Users/ALEX/AppData/LocalLow/Unity/WebPlayer/Cache/DefaultCompany_NewAtlantisNewUnity/fda28c6ebdbbaa0f7baaa89f97d964109ab0fde7/__data

And also 

Non-convex MeshCollider with non-kinematic Rigidbody is no longer supported in Unity 5.
If you want to use a non-convex mesh either make the Rigidbody kinematic or remove the Rigidbody component. Scene hierarchy path "root_space/JulietteAllocatedID: 12/Test4684/Sphere/Plane/Plane (12)", Mesh asset path "Library/unity default resources" Mesh name "Plane"

Do you think Unity 5.3 is relyable ? I now it's actually a beta version.
Maybe I will revert to 5.2 .
Any hints ?

**Comment by sachaamm** [comment]
This is a screenshot related to the issue 
![ensci test space](https://cloud.githubusercontent.com/assets/11826078/11790644/7b4f2a60-a262-11e5-9e32-855ef22dd9da.png)

**Comment by sachaamm** [comment]
Anyway , I just realized it's not a matter about ENSCI space but about Unity version not actually relyable, so I will switch to 5.2

**Comment by jonlab** [comment]
It seems that the Asset Bundle format changed so Unity is complaining about the older ones. I will look at this tomorrow.
