### ISSUE TITLE
Asset Bundles already loaded issue

### ISSUE THREAD

**Issue by sachaamm** [jonlab/NewAtlantis#45]
We are actually unable to load the Chicago space .
The Unity exception I get when loading the space is : 

The AssetBundle 'http://tanant.info/newatlantis2/objects/object_564a09f49e4000.49203890.unity3d' can't be loaded because another AssetBundle with the same files is already loaded.

I don't understand how , it happened with the Mark's city object.

**Comment by sachaamm** [comment]
The NADownloader process hold on and the last object to load is never loaded , I thought it was specific to the object but it's not . The process is never over even the last object is upoloaded ( in this case Immeuble turquoise )

**Comment by jonlab** [comment]
This is the Unload() in NAObject. I commented it for a test. I put it back again. It seems to work !

**Comment by jonlab** [comment]
(it happened because of a duplicate object/Asset Bundle in Space)
