### ISSUE TITLE
Crash after fall from the ENSCI platform

### ISSUE THREAD

**Issue by sachaamm** [jonlab/NewAtlantis#46]
Hi , sorry to point out another crash scenario from my side , but after downloaded the ENSCI space and falls from the start platform, I got crash from the NA client ( application exit with an system error message ) 
In the crash output log i got this last 3 lines : 
0x014D279E (NA_App_Windows) [f:\dd\vctools\crt_bld\self_x86\crt\src\crt0.c:275] __tmainCRTStartup 
0x7730337A (kernel32) BaseThreadInitThunk
0x77949882 (ntdll) RtlInitializeExceptionChain

Why the application is trying to get access from f:/ ? What is f:/ ? 
Maybe my graphic card ? 

[output_log.txt](https://github.com/jonlab/NewAtlantis/files/67609/output_log.txt)

**Comment by jonlab** [comment]
Are you able to reproduce ?

**Comment by sachaamm** [comment]
yes , it's happening everytime

**Comment by jonlab** [comment]
always when you fall from the platform ? If you don't, does it crash ? Could you post another log ?
From what I can see, it seems to be something in the rendering :
0x010C5490 (NA_App_Windows) [c:\buildslave\unity\build\runtime\shaders\shader.cpp:318] Shader::GetActiveSubShaderIndex 
0x00ED0BE0 (NA_App_Windows) [c:\buildslave\unity\build\runtime\camera\shadows.cpp:1317] PrepareShadowMapsJob 
0x00F2C27B (NA_App_Windows) [c:\buildslave\unity\build\runtime\jobs\internal\jobqueue.cpp:338] JobQueue::Exec 
0x00F2B900 (NA_App_Windows) [c:\buildslave\unity\build\runtime\jobs\internal\jobqueue.cpp:441] JobQueue::Steal 
0x00F2C55A (NA_App_Windows) [c:\buildslave\unity\build\runtime\jobs\internal\jobqueue.cpp:1170] JobQueue::WaitForJobGroup 
0x00F2B23C (NA_App_Windows) [c:\buildslave\unity\build\runtime\jobs\jobs.cpp:27] CompleteFenceInternal 
0x00ED2E02 (NA_App_Windows) [c:\buildslave\unity\build\runtime\camera\shadows.cpp:1770] RenderShadowMaps

**Comment by jonlab** [comment]
(this is crashing in Unity so apart from trying to understand and avoid the cause, we cannot fix anything)
