### ISSUE TITLE
Space teleporter

### ISSUE THREAD

**Issue by jonlab** [jonlab/NewAtlantis#5]
The current Space teleporter script (NASpaceTeleportOnTrigger) allow any collision to trigger a Space change for every user connected to this session. The user's position then change to a given position : fixed, in a given volume ? TBD

**Comment by jonlab** [comment]
Do we need to decide that the center area of every space is a "spawning zone" and then needs to be kept clear of any objects ?

**Comment by rolandcahen** [comment]
The user is responsible. Let's not do anything now. Users must organize their spaces. If they want to be ejected when teleported, they can.

**Comment by jonlab** [comment]
ok, let's do that. We'll see how it works. This is currently implemented as a fixed target spawning point : everyone is spawned at the same position and Physics engine will do the rest (don't do that in the real world ;-) ).
