### ISSUE TITLE
submodule error when cloning

### ISSUE THREAD

**Issue by benchang02** [jonlab/NewAtlantis#51]
Just did a fresh clone and got this odd error:

```
git -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree submodule update --init --recursive 
No submodule mapping found in .gitmodules for path 'NewAtlantis'
```

then in Unity I get this compiler errors:

```
Removing Assets/NewAtlantis/Users/Scripts/alex_scripts because the asset does not exist
```

and the same for Scripts/alexandre, Characters/PhysicsMaterials and Characters/ThirdPersonCharacter.

**Comment by sachaamm** [comment]
Ok , are you able to load the scene ?
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
This
email has been sent from a virus-free computer protected by Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2016-01-04 22:17 GMT-06:00 benchang02 <notifications@github.com>:

**Comment by benchang02** [comment]
Still the same git error when pulling.  In Unity the errors are gone because the files/directories have been deleted.  Seems like it had a .meta file for those files but not the files themselves?  But are those files supposed to be there?

**Comment by sachaamm** [comment]
Ok , Are you able to load the scene ? 
I tried a git clone which was succesful , you use a github client ?

**Comment by sachaamm** [comment]
or you use git in a terminal ?

**Comment by sachaamm** [comment]
No theses files are not supposed to be there .

**Comment by benchang02** [comment]
ok, should be fine then.  But it's strange, I get three top-level directories: Images, NewAtlantis, and NewAtlantisUnity. "NewAtlantisUnity" has all the source, but "NewAtlantis" is empty although I see commit messages referring to things being in there.  looking at the github site in a web browser,that directory has a gray icon that I don't recognize, and I can't go into it - any idea what's going on with it?

**Comment by sachaamm** [comment]
Yes , SORRY Ben ! It was a git submodule .. Now it's fix :)

**Comment by sachaamm** [comment]
It was a recursive problem , the repository was cloning content into a submodule (itself)
