### ISSUE TITLE
Can we get a keyboard fallback for the tool Panel?

### ISSUE THREAD

**Issue by sachaamm** [jonlab/NewAtlantis#53]
Can we get a keyboard fallback for the tool Panel?
we cannot put secondary input for DPadX and DPadY

**Comment by jonlab** [comment]
Yes, this is already implemented with the mouse : see the doc https://github.com/jonlab/NewAtlantis/wiki/Controls
However, there is an issue when your screen height is < 768. I will try to fix it.

**Comment by jonlab** [comment]
fixed and commited.
