### ISSUE TITLE
unsaved changes are destructive

### ISSUE THREAD

**Issue by rolandcahen** [jonlab/NewAtlantis#54]
Deleting a composition/object in admin rights are saved even if the save button is not pressed.
I have destroyed compositions from ENSCI space trying to delete them momentally from teh space to find out about possible sound issues and had to reconstitute them

**Comment by jonlab** [comment]
yes, this is intended. Delete means delete and this is immediate. And this is why we put admin rights. When you are admin you are able to delete. If you want to temporarily remove objects, hide or delete them in the Unity scene, not using the delete feature.
