### ISSUE TITLE
Can not connect to a running server

### ISSUE THREAD

**Issue by zozizozu** [jonlab/NewAtlantis#56]
![navservwontconn](https://cloud.githubusercontent.com/assets/18497192/14580173/284ae510-03c5-11e6-8c03-c32f0f03fb7c.png)

Hi, i'm trying to connect to a running server ( see attached pic ) , but it fail.
Am i doing something wrong ( i just copy/paste the server's ip and click "join") ? 
Is there a documentation about running and connecting to a server ?
Thanks,

**Comment by jonlab** [comment]
Yes, we had some issues with the network at the Palais de Tokyo in Paris (where New Atlantis project was in demo). The ability to be able to connect or not depends on the network (NAT punchthrough has to work and this is not guarranteed).
