### ISSUE TITLE
The type or namespace name `MatchDesc' could not be found. NA Uncompatibility with Unity 5.4 ?

### ISSUE THREAD

**Issue by sachaamm** [jonlab/NewAtlantis#57]
When I clone the github project , after open it , I got this error : 

Assets/NewAtlantis/Core/Scripts/networking_tests/HostGame.cs(9,14): error CS0246: The type or namespace name `MatchDesc' could not be found. Are you missing a using directive or an assembly reference?

Is it a compatibility issue with Unity 5.4 ? Does anyone else already caught this error ?
( W10 / VS2015 / Unity5.4.0f3 )

**Comment by jonlab** [comment]
This is fixed in last version (was an deprecated API call).
